name = "Sourcepawn"
grammar = "sourcepawn"
path_suffixes = ["sp", "inc", "games.txt", "phrases.txt", "cfg"]
line_comments = ["// "]
documentation = { start = "/*", end = "*/", prefix = "* ", tab_size = 1 }
